package com.maellakioa.models;

// Generated Nov 1, 2014 10:08:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persons generated by hbm2java
 */
@Entity
@Table(name = "persons", catalog = "personsdb")
public class Person {

	private Long id;
	private String name;
	private byte age;

	public Person() {
	}

	public Person(String name, byte age) {
		this.name = name;
		this.age = age;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", nullable = false)
	public byte getAge() {
		return this.age;
	}

	public void setAge(byte age) {
		this.age = age;
	}

}
